describe('Alerts management', () => {

  before(function(){
    cy.fixture('store').then(function(data)
    {
      this.data=data 
    })
  })

  beforeEach(() => {
    cy.login();
  });

  it('Access Alerts page', function() {
    cy.loginCoop();
    
    cy.allure().tag('smoke');
    cy.allure().severity('critical');

    cy.loginCoop()
    
    //Click Alerts tab
    cy.get('[href="/alerts"] > .inline-flex > .text-sm').click()

    //Assert Alerts page is accessed using url
    cy.url().should('include', '/alerts')

    //Check if there are alerts
    cy.get('.p-0 > .justify-between > :nth-child(2)')
      .contains('Showing ').should('contain', '1 - 19 of 19 entries')
  })

  it('Alerts filter: by Status', function() {
    
    cy.loginCoop()
    
    //Click Alerts tab
    cy.get('[href="/alerts"] > .inline-flex > .text-sm').click()
    
    //Assert Alerts page is accessed using url
    cy.url().should('include', '/alerts')
    
    //Status filter
    
    cy.contains('label', 'Status')
      .parent()
      .find('button[role="combobox"]')
      .click()
    
    cy.contains('[role="option"]', 'Open')
      .should('be.visible')
      .click()
    
    //Assertion
    //cy.get('.w-full.caption-bottom.text-sm')
    cy.get('tr td:nth-child(6)').each(($el, index, $list) => {
    
      const text = $el.text()
      if(text.includes('Critical'))
      {
        cy.get('tr td:nth-child(6)').eq(index).next().then(function(status){
          const statusText = status.text()
          expect(statusText).to.equal('Open')
        })
      }
    
    })
    
  })

  it('Assign Open Alert to a Fraud Analyst', function() {
    
    cy.loginCoop()
    
    //Click Alerts tab
    cy.get('[href="/alerts"] > .inline-flex > .text-sm').click()
    
    //Assert Alerts page is accessed using url
    cy.url().should('include', '/alerts')
    
    //Status filter
    
    cy.contains('label', 'Status')
      .parent()
      .find('button[role="combobox"]')
      .click()
    
    cy.contains('[role="option"]', 'Open')
      .should('be.visible')
      .click()
    
    //Assertion for open alerts
    //cy.get('.w-full.caption-bottom.text-sm')
    cy.get('tr td:nth-child(6)').each(($el, index, $list) => {
    
      const text = $el.text()
      if(text.includes('Critical'))
      {
        cy.get('tr td:nth-child(6)').eq(index).next().then(function(status){
          const statusText = status.text()
          expect(statusText).to.equal('Open')
        })
      }
    
    })

    cy.get('tr td:nth-child(9)').each(($el, index) => {

      const viewDetails = $el.text().trim()

      if (viewDetails.includes('Jan 27, 2026, 3:43 PM EAT')) {

        // Move to the "Action" cell in the SAME row
        cy.get('tr td:nth-child(9)')
          .eq(index)
          .next()
          .contains('View details')   // find the button/link
          .should('be.visible')
          .click()

          //Assert to check detail page of the alert is accessed
        cy.wait(1500)
        //cy.url().should('include', '/48d01543-d9f5-4ab4-a689-481330e461cf') 
        cy.get('.p-8').should('contain', 'Generated by rule Check Blacklisted Customer')
      }     
    })

    //Click on Assign button
    cy.contains('button', 'Assign').click()

    //Assign to Coop Analyst
    cy.wait(1000)
    
    // Open dropdown
    cy.get('#assignTo')
      .should('be.visible')
      .click()

    // Choose option
    cy.contains('[role="option"]', 'Coop Analyst2 (coopanalyst2)', { timeout: 10000 })
      .click()

    // Verify
    cy.get('button[role="combobox"]')
      .should('contain', 'Coop Analyst2 (coopanalyst2)')

    //Click Assign button on the dialog box
    cy.get('div[role="dialog"]')
      .contains('button', 'Assign')
      .click()

    //Assert the alert is assigned to Coop Analyst
    cy.get(':nth-child(7) > .mt-1')
      .should('contain', 'coopanalyst2')
    
  })

  it.only('Transfer assigned Alert to another Fraud Analyst', function() {
    
    cy.visit('https://admin.detect.kifiya.dev/auth')
    cy.get('#login-username').type(this.data.email)
    cy.get('#login-password').type(this.data.password)
    
    cy.get('#login-tenant').as('TenantSelector') //Aliasing the tenant selection
    cy.get('@TenantSelector').select(this.data.tenant) //Select Coop tenant
    
    //Assertion to check the selection of coop tenant
    cy.get('@TenantSelector')
      .select(this.data.tenant)
      .should('have.value', 'COOP')
    
    //Click Login and Assert the login
    cy.get('.inline-flex').click()
    cy.url().should('include', '/dashboard')
    
    //Click Alerts tab
    cy.get('[href="/alerts"] > .inline-flex > .text-sm').click()
    
    //Assert Alerts page is accessed using url
    cy.url().should('include', '/alerts')
    
    //Status filter
    
    cy.contains('label', 'Status')
      .parent()
      .find('button[role="combobox"]')
      .click()
    
    cy.contains('[role="option"]', 'Assigned')
      .should('be.visible')
      .click()
    
    //Assertion for assigned alerts
    //cy.get('.w-full.caption-bottom.text-sm')
    cy.wait(2000)
    cy.get('tr td:nth-child(6)').each(($el, index, $list) => {
    
      const text = $el.text()
      if(text.includes('Critical'))
      {
        cy.get('tr td:nth-child(6)').eq(index).next().then(function(status){
          const statusText = status.text()
          expect(statusText).to.equal('Assigned')
        })
      }
    
    })

    //View details of an assigned alert
    cy.get('tr td:nth-child(9)').each(($el, index) => {

      const viewDetails = $el.text().trim()

      if (viewDetails.includes('Jan 26, 2026, 3:31 PM EAT')) {

        // Move to the "Action" cell in the SAME row
        cy.get('tr td:nth-child(9)')
          .eq(index)
          .next()
          .contains('View details')   // find the button/link
          .should('be.visible')
          .click()

          //Assert to check detail page of the alert is accessed
        cy.wait(1500)
        //cy.url().should('include', '/48d01543-d9f5-4ab4-a689-481330e461cf') 
        cy.get('.p-8').should('contain', 'Generated by rule Check Blacklisted Customer')
      }     
    })

    //Click on Transfer button
    cy.contains('button', 'Transfer').click()

    //Assign to Coop Analyst
    cy.wait(1000)
    
    // Open dropdown
    cy.get('#transferTo')
      .should('be.visible')
      .click()

    // Choose option
    cy.contains('[role="option"]', 'Coop Analyst2 (coopanalyst2)', { timeout: 10000 })
      .click()

    // Verify
    cy.get('button[role="combobox"]')
      .should('contain', 'Coop Analyst2 (coopanalyst2)')

    //Click Assign button on the dialog box
    cy.get('div[role="dialog"]')
      .contains('button', 'Transfer')
      .click()

    //Assert the alert is transfered to Coop Analyst2
    cy.get(':nth-child(7) > .mt-1')
      .should('contain', 'coopanalyst2')
    
  })

  it('Close an alert', function() {
    
    cy.visit('https://admin.detect.kifiya.dev/auth')
    cy.get('#login-username').type(this.data.email)
    cy.get('#login-password').type(this.data.password)
    
    cy.get('#login-tenant').as('TenantSelector') //Aliasing the tenant selection
    cy.get('@TenantSelector').select(this.data.tenant) //Select Coop tenant
    
    //Assertion
    cy.get('@TenantSelector')
      .select(this.data.tenant)
      .should('have.value', 'COOP')
    
    //Click Login and Assert
    cy.get('.inline-flex').click()
    cy.url().should('include', '/dashboard')
    
    //Click Alerts tab
    cy.get('[href="/alerts"] > .inline-flex > .text-sm').click()
    
    //Assert Alerts page is accessed using url
    cy.url().should('include', '/alerts')
    
    //Status filter
    
    cy.contains('label', 'Status')
      .parent()
      .find('button[role="combobox"]')
      .click()
    
    cy.contains('[role="option"]', 'Assigned')
      .should('be.visible')
      .click()
    
    //Assertion for assigned alerts
    //cy.get('.w-full.caption-bottom.text-sm')
    cy.get('tr td:nth-child(6)').each(($el, index, $list) => {
    
      const text = $el.text()
      if(text.includes('Critical'))
      {
        cy.get('tr td:nth-child(6)').eq(index).next().then(function(status){
          const statusText = status.text()
          expect(statusText).to.equal('Assigned')
        })
      }
    
    })

    cy.get('tr td:nth-child(9)').each(($el, index) => {

      const viewDetails = $el.text().trim()

      if (viewDetails.includes('Jan 27, 2026, 3:43 PM EAT')) {

        // Move to the "Action" cell in the SAME row
        cy.get('tr td:nth-child(9)')
          .eq(index)
          .next()
          .contains('View details')   // find the button/link
          .should('be.visible')
          .click()

          //Assert to check detail page of the alert is accessed
        cy.wait(1500)
        //cy.url().should('include', '/48d01543-d9f5-4ab4-a689-481330e461cf') 
        cy.get('.p-8').should('contain', 'Generated by rule Check Blacklisted Customer')
      }     
    })

    //Click on Assign button
    cy.contains('button', 'Close alert').click()

    //Assign to Coop Analyst
    cy.wait(2000)
    
    //Assert the alert is closed
  })

})